{
    'name': "custom Report",
    'summary': """Custom Report""",
    'version': '16.0.1.0.2',
    'description': """Custom Report""",
    'category': '',
    'author': '',
    'company': '',
    'website': "",
    'depends': ['base', 'purchase', 'account', 'custom_csf', 'sale',
                'custom_price'],
    'data': [
        'views/purchase_report.xml',
        'views/invoice_report.xml',
        'views/sale_report.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
