from . import product
from . import website
from . import sale_order
from . import account_move
from . import partner
from . import quotaion_wizard
from . import rfq_wizard
from . import purchase
from . import channels
