{
    'name': "custom product",
    'summary': """Custom Product""",
    'version': '16.0.3.5.5',
    'description': """Custom Product""",
    'category': '',
    'author': '',
    'company': '',
    'website': "",
    'depends': ['base', 'product', 'stock', 'stock_account', 'sale',
                'website_sale', 'website', 'l10n_mx_edi_extended',
                'account', 'l10n_mx_edi', 'delivery', 'purchase',
                'l10n_mx_edi_stock', 'base_address_extended',
                'account', 'l10n_mx_edi_40'],
    'data': [
        'security/ir.model.access.csv',
        'views/quotation_wizard.xml',
        'views/sale_order.xml',
        'views/rfq_wizard.xml',
        'views/product.xml',
        'views/product_template.xml',
        'views/partner.xml',
        'views/partner_inv.xml',
        'views/channel.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
